# Generated by Django 5.2.8 on 2025-11-22 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSkripsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_skripsi', models.TextField()),
                ('abstrak', models.TextField(blank=True, null=True)),
                ('kategori_topik', models.CharField(blank=True, max_length=100, null=True)),
                ('kata_kunci', models.CharField(blank=True, max_length=255, null=True)),
                ('tahun_lulus', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RekomendasiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor_kemiripan', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('alasan_rekomendasi', models.TextField(blank=True, null=True)),
                ('tanggal_rekomendasi', models.DateTimeField(auto_now_add=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekomendasi_logs', to='accounts.mahasiswa')),
                ('skripsi_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender.datasetskripsi')),
            ],
        ),
        migrations.CreateModel(
            name='TranskripUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='transkrip/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('semester_berjalan', models.IntegerField(blank=True, null=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transkrip_uploads', to='accounts.mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='TranskripDetailNilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mk', models.CharField(blank=True, max_length=20, null=True)),
                ('nama_mk', models.CharField(max_length=255)),
                ('sks', models.IntegerField()),
                ('nilai_huruf', models.CharField(blank=True, max_length=2, null=True)),
                ('angka_mutu', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('bobot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_nilai', to='recommender.transkripupload')),
            ],
        ),
    ]
